# Generated by Django 6.1 on 2026-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "company_size",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("budget", models.PositiveIntegerField(blank=True, null=True)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                (
                    "questionnaire_response",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "pk"],
            },
        ),
    ]
