# Generated by Django 6.1 on 2026-08-26 18:36

import django.core.validators
import django.db.models.deletion
import vinta_django_questionnaires.schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier, shared by every version.",
                        max_length=100,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal name. The title shown to respondents lives on each version.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "questionnaire",
                "verbose_name_plural": "questionnaires",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="key"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier of the client-side component, when it differs from the key.",
                        max_length=255,
                        verbose_name="component",
                    ),
                ),
                (
                    "props_schema",
                    models.JSONField(
                        default=vinta_django_questionnaires.schemas.permissive_object_schema,
                        help_text="JSON Schema (draft 2020-12) the question's widget props must satisfy.",
                        verbose_name="props schema",
                    ),
                ),
                (
                    "default_props",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="default props"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "questionnaire widget",
                "verbose_name_plural": "questionnaire widgets",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="vinta_django_questionnaires.questionnaire",
                        verbose_name="questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "questionnaire version",
                "verbose_name_plural": "questionnaire versions",
                "ordering": ["questionnaire", "-version"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JMESPath expression returning a boolean, evaluated against the answers. Leave empty to always include this item.",
                        verbose_name="condition",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique within the version.",
                        max_length=100,
                        verbose_name="key",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="conclusion",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["questionnaire_version", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JMESPath expression returning a boolean, evaluated against the answers. Leave empty to always include this item.",
                        verbose_name="condition",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique within the questionnaire version. Answers are keyed by it.",
                        max_length=100,
                        verbose_name="key",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("free_text", "Free text"),
                            ("single_select", "Single select from a value set"),
                            ("multi_select", "Multi select from a value set"),
                            ("number", "Number"),
                            ("number_range", "Number range"),
                            ("time", "Time"),
                            ("date", "Date"),
                            ("date_time", "Date and time"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("date_range", "Date range"),
                            ("date_time_range", "Date and time range"),
                            ("time_duration", "Time duration"),
                            ("url", "URL"),
                            ("single_file", "Single file"),
                            ("multiple_files", "Multiple files"),
                            ("binary_matrix", "Binary matrix of selections"),
                            ("item_list", "List of items"),
                            ("sub_questionnaire", "Sub-questionnaire"),
                            ("sub_questionnaire_list", "List of sub-questionnaires"),
                        ],
                        max_length=50,
                        verbose_name="question type",
                    ),
                ),
                (
                    "requires_being_first_in_a_row",
                    models.BooleanField(
                        default=False, verbose_name="requires being first in a row"
                    ),
                ),
                (
                    "requires_being_last_in_a_row",
                    models.BooleanField(
                        default=False, verbose_name="requires being last in a row"
                    ),
                ),
                (
                    "widget_props",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Checked against the widget's props schema on save.",
                        verbose_name="widget props",
                    ),
                ),
                (
                    "allows_other",
                    models.BooleanField(
                        default=False,
                        help_text="Adds a free text escape hatch to a choice question.",
                        verbose_name="allows other",
                    ),
                ),
                (
                    "other_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="other label",
                    ),
                ),
                (
                    "item_question_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("free_text", "Free text"),
                            ("single_select", "Single select from a value set"),
                            ("multi_select", "Multi select from a value set"),
                            ("number", "Number"),
                            ("number_range", "Number range"),
                            ("time", "Time"),
                            ("date", "Date"),
                            ("date_time", "Date and time"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("date_range", "Date range"),
                            ("date_time_range", "Date and time range"),
                            ("time_duration", "Time duration"),
                            ("url", "URL"),
                            ("single_file", "Single file"),
                            ("multiple_files", "Multiple files"),
                            ("binary_matrix", "Binary matrix of selections"),
                            ("item_list", "List of items"),
                            ("sub_questionnaire", "Sub-questionnaire"),
                            ("sub_questionnaire_list", "List of sub-questionnaires"),
                        ],
                        default="",
                        help_text="The type of each item of a list of items.",
                        max_length=50,
                        verbose_name="item question type",
                    ),
                ),
                (
                    "sub_questionnaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referencing_questions",
                        to="vinta_django_questionnaires.questionnaire",
                        verbose_name="sub-questionnaire",
                    ),
                ),
                (
                    "sub_questionnaire_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pin a version, or leave empty to follow the latest published one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referencing_questions",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="sub-questionnaire version",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to use the default widget of the question type.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="vinta_django_questionnaires.questionnairewidget",
                        verbose_name="widget",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["section", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="QuestionValidator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "validator",
                    models.CharField(
                        help_text="Key the validator is registered under.",
                        max_length=100,
                        verbose_name="validator",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="params"),
                ),
                (
                    "message_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Maps one of the validator's error keys to the message to show instead.",
                        verbose_name="message overrides",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="is enabled"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validators",
                        to="vinta_django_questionnaires.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question validator",
                "verbose_name_plural": "question validators",
                "ordering": ["question", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JMESPath expression returning a boolean, evaluated against the answers. Leave empty to always include this item.",
                        verbose_name="condition",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique within the page.",
                        max_length=100,
                        verbose_name="key",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="conclusion",
                    ),
                ),
                (
                    "default_state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                        verbose_name="default state",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="vinta_django_questionnaires.page",
                        verbose_name="page",
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ["page", "order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="vinta_django_questionnaires.section",
                verbose_name="section",
            ),
        ),
        migrations.CreateModel(
            name="ValueSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="key"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown is supported.",
                        verbose_name="description",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("static", "Static options"),
                            ("model", "Model queryset"),
                            ("endpoint", "Endpoint"),
                        ],
                        default="static",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "filter_expression",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Filter DSL, e.g. \'status = "active" and not slug in ["internal"]\'.',
                        verbose_name="filter expression",
                    ),
                ),
                (
                    "value_field",
                    models.CharField(
                        blank=True,
                        default="pk",
                        help_text="Field read for the option value.",
                        max_length=100,
                        verbose_name="value field",
                    ),
                ),
                (
                    "label_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Field read for the option label. Empty falls back to str(instance).",
                        max_length=100,
                        verbose_name="label field",
                    ),
                ),
                (
                    "ordering",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma separated field names, '-' prefixed to reverse.",
                        max_length=255,
                        verbose_name="ordering",
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True, default="", verbose_name="endpoint URL"
                    ),
                ),
                (
                    "endpoint_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="GET",
                        max_length=10,
                        verbose_name="endpoint method",
                    ),
                ),
                (
                    "endpoint_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="endpoint headers"
                    ),
                ),
                (
                    "endpoint_query_params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="endpoint query params"
                    ),
                ),
                (
                    "endpoint_results_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="JMESPath to the list of options in the response body.",
                        max_length=255,
                        verbose_name="endpoint results path",
                    ),
                ),
                (
                    "endpoint_value_path",
                    models.CharField(
                        blank=True,
                        default="value",
                        help_text="JMESPath to the value inside one result.",
                        max_length=255,
                        verbose_name="endpoint value path",
                    ),
                ),
                (
                    "endpoint_label_path",
                    models.CharField(
                        blank=True,
                        default="label",
                        help_text="JMESPath to the label inside one result.",
                        max_length=255,
                        verbose_name="endpoint label path",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questionnaire_value_sets",
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
            ],
            options={
                "verbose_name": "value set",
                "verbose_name_plural": "value sets",
                "ordering": ["key"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="value_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="vinta_django_questionnaires.valueset",
                verbose_name="value set",
            ),
        ),
        migrations.CreateModel(
            name="ValueSetOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("value", models.CharField(max_length=255, verbose_name="value")),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="extra"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "value_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="vinta_django_questionnaires.valueset",
                        verbose_name="value set",
                    ),
                ),
            ],
            options={
                "verbose_name": "value set option",
                "verbose_name_plural": "value set options",
                "ordering": ["value_set", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="WidgetQuestionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single choice"),
                            ("multiple_choice", "Multiple choice"),
                            ("free_text", "Free text"),
                            ("single_select", "Single select from a value set"),
                            ("multi_select", "Multi select from a value set"),
                            ("number", "Number"),
                            ("number_range", "Number range"),
                            ("time", "Time"),
                            ("date", "Date"),
                            ("date_time", "Date and time"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("date_range", "Date range"),
                            ("date_time_range", "Date and time range"),
                            ("time_duration", "Time duration"),
                            ("url", "URL"),
                            ("single_file", "Single file"),
                            ("multiple_files", "Multiple files"),
                            ("binary_matrix", "Binary matrix of selections"),
                            ("item_list", "List of items"),
                            ("sub_questionnaire", "Sub-questionnaire"),
                            ("sub_questionnaire_list", "List of sub-questionnaires"),
                        ],
                        max_length=50,
                        verbose_name="question type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used by questions of this type that do not name a widget.",
                        verbose_name="is default",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_type_supports",
                        to="vinta_django_questionnaires.questionnairewidget",
                        verbose_name="widget",
                    ),
                ),
            ],
            options={
                "verbose_name": "widget question type",
                "verbose_name_plural": "widget question types",
                "ordering": ["widget", "question_type"],
            },
        ),
        migrations.CreateModel(
            name="WindowSizeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("key", models.SlugField(verbose_name="key")),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="label"
                    ),
                ),
                (
                    "min_width",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="In pixels, inclusive.",
                        verbose_name="minimum width",
                    ),
                ),
                (
                    "max_width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="In pixels, inclusive. Leave empty for an unbounded range.",
                        null=True,
                        verbose_name="maximum width",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="window_size_ranges",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
            ],
            options={
                "verbose_name": "window size range",
                "verbose_name_plural": "window size ranges",
                "ordering": ["questionnaire_version", "order", "min_width"],
            },
        ),
        migrations.CreateModel(
            name="QuestionMinimumColumns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "minimum_columns",
                    models.PositiveSmallIntegerField(
                        default=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="minimum columns",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minimum_columns",
                        to="vinta_django_questionnaires.question",
                        verbose_name="question",
                    ),
                ),
                (
                    "window_size_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_minimum_columns",
                        to="vinta_django_questionnaires.windowsizerange",
                        verbose_name="window size range",
                    ),
                ),
            ],
            options={
                "verbose_name": "question minimum columns",
                "verbose_name_plural": "question minimum columns",
            },
        ),
        migrations.CreateModel(
            name="LayerColumns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "columns",
                    models.PositiveSmallIntegerField(
                        default=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="columns",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_columns",
                        to="vinta_django_questionnaires.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_columns",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_columns",
                        to="vinta_django_questionnaires.section",
                        verbose_name="section",
                    ),
                ),
                (
                    "window_size_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_columns",
                        to="vinta_django_questionnaires.windowsizerange",
                        verbose_name="window size range",
                    ),
                ),
            ],
            options={
                "verbose_name": "layer columns",
                "verbose_name_plural": "layer columns",
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "axis",
                    models.CharField(
                        choices=[
                            ("option", "Option"),
                            ("row", "Matrix row"),
                            ("column", "Matrix column"),
                        ],
                        default="option",
                        max_length=10,
                        verbose_name="axis",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="value")),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="extra"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="vinta_django_questionnaires.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question choice",
                "verbose_name_plural": "question choices",
                "ordering": ["question", "axis", "order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "axis", "value"),
                        name="unique_choice_value_per_question_axis",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="questionnaireversion",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "version"),
                name="unique_version_per_questionnaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("questionnaire_version", "key"),
                name="unique_page_key_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("page", "key"), name="unique_section_key_per_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("section", "key"), name="unique_question_key_per_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="valuesetoption",
            constraint=models.UniqueConstraint(
                fields=("value_set", "value"), name="unique_option_value_per_value_set"
            ),
        ),
        migrations.AddConstraint(
            model_name="widgetquestiontype",
            constraint=models.UniqueConstraint(
                fields=("widget", "question_type"),
                name="unique_question_type_per_widget",
            ),
        ),
        migrations.AddConstraint(
            model_name="widgetquestiontype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("question_type",),
                name="unique_default_widget_per_question_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="windowsizerange",
            constraint=models.UniqueConstraint(
                fields=("questionnaire_version", "key"),
                name="unique_window_size_range_key_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="windowsizerange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_width__isnull", True),
                    ("max_width__gt", models.F("min_width")),
                    _connector="OR",
                ),
                name="window_size_range_max_width_above_min_width",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionminimumcolumns",
            constraint=models.UniqueConstraint(
                fields=("question", "window_size_range"),
                name="unique_minimum_columns_per_question_and_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="layercolumns",
            constraint=models.UniqueConstraint(
                fields=("questionnaire_version", "window_size_range"),
                name="unique_columns_per_version_and_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="layercolumns",
            constraint=models.UniqueConstraint(
                fields=("page", "window_size_range"),
                name="unique_columns_per_page_and_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="layercolumns",
            constraint=models.UniqueConstraint(
                fields=("section", "window_size_range"),
                name="unique_columns_per_section_and_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="layercolumns",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("page__isnull", True),
                        ("questionnaire_version__isnull", False),
                        ("section__isnull", True),
                    ),
                    models.Q(
                        ("page__isnull", False),
                        ("questionnaire_version__isnull", True),
                        ("section__isnull", True),
                    ),
                    models.Q(
                        ("page__isnull", True),
                        ("questionnaire_version__isnull", True),
                        ("section__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="layer_columns_belong_to_exactly_one_layer",
            ),
        ),
    ]
