# Generated by Django 6.1 on 2026-08-26 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinta_django_questionnaires", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_skippable",
            field=models.BooleanField(
                default=False,
                help_text="Whether the respondent may leave this page for later and move on.",
                verbose_name="is skippable",
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Identifies a respondent that is not a user of this system.",
                        max_length=255,
                        verbose_name="external id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data conditions may read alongside the answers, such as the respondent's role. An answer with the same key wins.",
                        verbose_name="context",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questionnaire_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="respondent",
                    ),
                ),
            ],
            options={
                "verbose_name": "questionnaire response",
                "verbose_name_plural": "questionnaire responses",
                "ordering": ["-created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PageResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("skipped", "Skipped")],
                        default="completed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual_action", "Skipped by the respondent"),
                            ("false_condition", "Condition did not hold"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="skip reason",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="vinta_django_questionnaires.page",
                        verbose_name="page",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_responses",
                        to="vinta_django_questionnaires.questionnaireresponse",
                        verbose_name="response",
                    ),
                ),
            ],
            options={
                "verbose_name": "page response",
                "verbose_name_plural": "page responses",
                "ordering": ["response", "page__order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "value",
                    models.JSONField(blank=True, null=True, verbose_name="value"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="vinta_django_questionnaires.question",
                        verbose_name="question",
                    ),
                ),
                (
                    "page_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="vinta_django_questionnaires.pageresponse",
                        verbose_name="page response",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_records",
                        to="vinta_django_questionnaires.questionnaireresponse",
                        verbose_name="response",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "ordering": ["response", "question__order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="pageresponse",
            constraint=models.UniqueConstraint(
                fields=("response", "page"), name="unique_page_response_per_response"
            ),
        ),
        migrations.AddConstraint(
            model_name="pageresponse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("skip_reason", ""), ("status", "completed")),
                    models.Q(
                        ("status", "skipped"),
                        models.Q(("skip_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="page_response_skip_reason_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"),
                name="unique_answer_per_response_and_question",
            ),
        ),
    ]
