# Generated by Django 6.1 on 2026-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vinta_django_questionnaires",
            "0002_page_is_skippable_questionnaireresponse_pageresponse_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireversion",
            name="edit_policy",
            field=models.CharField(
                choices=[
                    ("never", "Never: a page is final once it is recorded"),
                    (
                        "until_completed",
                        "Until completed: pages can be revised while the response is in progress",
                    ),
                    ("always", "Always: a completed response can still be changed"),
                ],
                default="until_completed",
                max_length=20,
                verbose_name="edit policy",
            ),
        ),
        migrations.AddField(
            model_name="questionnaireversion",
            name="edits_due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="After this moment no recorded answer can be changed. Empty means no deadline.",
                null=True,
                verbose_name="edits due at",
            ),
        ),
        migrations.AddField(
            model_name="questionnaireversion",
            name="responses_due_at",
            field=models.DateTimeField(
                blank=True,
                help_text="After this moment no page can be answered. Empty means no deadline.",
                null=True,
                verbose_name="responses due at",
            ),
        ),
    ]
