# Generated by Django 6.1 on 2026-08-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "vinta_django_questionnaires",
            "0003_questionnaireversion_edit_policy_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcknowledgedEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="object id"
                    ),
                ),
                (
                    "target_label",
                    models.CharField(max_length=100, verbose_name="target"),
                ),
                (
                    "target_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="target key",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=10,
                        verbose_name="action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Each changed field, with the value before and after.",
                        verbose_name="changes",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="reason"),
                ),
                (
                    "responses_at_edit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many responses the version already had when this was done.",
                        verbose_name="responses at edit",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_questionnaire_edits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="acknowledged by",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledged_edits",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
            ],
            options={
                "verbose_name": "acknowledged edit",
                "verbose_name_plural": "acknowledged edits",
                "ordering": ["-created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["questionnaire_version", "-created_at"],
                        name="vinta_djang_questio_5574d2_idx",
                    )
                ],
            },
        ),
    ]
