# Generated by Django 6.1 on 2026-08-27 04:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vinta_django_questionnaires", "0004_acknowledgededit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JMESPath expression returning a boolean, evaluated against the answers. Leave empty to always include this item.",
                        verbose_name="condition",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="key"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_completion", "When the response is complete"),
                            ("on_page_submit", "Every time a page is pushed"),
                        ],
                        default="on_completion",
                        max_length=20,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("insert", "Insert a new record"),
                            ("update", "Update the record it finds"),
                            ("upsert", "Update the record it finds, or insert one"),
                        ],
                        default="insert",
                        max_length=10,
                        verbose_name="operation",
                    ),
                ),
                (
                    "defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Written alongside the mapped fields when a record is created. A mapped field with a value of its own wins.",
                        verbose_name="defaults",
                    ),
                ),
                (
                    "update_defaults",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the defaults are also written when an existing record is updated.",
                        verbose_name="apply defaults on update",
                    ),
                ),
                (
                    "skip_when_lookup_is_empty",
                    models.BooleanField(
                        default=True,
                        help_text="A lookup expression that resolves to nothing usually means the answer was not given. Skip rather than match every record.",
                        verbose_name="skip when the lookup is empty",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_mappings",
                        to="contenttypes.contenttype",
                        verbose_name="target model",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="vinta_django_questionnaires.questionnaire",
                        verbose_name="questionnaire",
                    ),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pin a version, or leave empty to run for every version of it.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
            ],
            options={
                "verbose_name": "response mapping",
                "verbose_name_plural": "response mappings",
                "ordering": ["questionnaire", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ResponseWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JMESPath expression returning a boolean, evaluated against the answers. Leave empty to always include this item.",
                        verbose_name="condition",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="key"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("on_completion", "When the response is complete"),
                            ("on_page_submit", "Every time a page is pushed"),
                        ],
                        default="on_completion",
                        max_length=20,
                        verbose_name="trigger",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="POST",
                        max_length=10,
                        verbose_name="method",
                    ),
                ),
                (
                    "url_template",
                    models.CharField(
                        help_text="May hold {placeholders}, each of which needs a URL parameter below.",
                        max_length=500,
                        verbose_name="URL template",
                    ),
                ),
                (
                    "url_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Maps each placeholder in the URL to the JMESPath expression that fills it.",
                        verbose_name="URL parameters",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Header name to value. Use {"$jmespath": "..."} for a value from the response.',
                        verbose_name="headers",
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Sent as JSON. Any {"$jmespath": "..."} in it is resolved first.',
                        verbose_name="body",
                    ),
                ),
                (
                    "timeout",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="In seconds.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="timeout",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="vinta_django_questionnaires.questionnaire",
                        verbose_name="questionnaire",
                    ),
                ),
                (
                    "questionnaire_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pin a version, or leave empty to run for every version of it.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="vinta_django_questionnaires.questionnaireversion",
                        verbose_name="questionnaire version",
                    ),
                ),
            ],
            options={
                "verbose_name": "response webhook",
                "verbose_name_plural": "response webhooks",
                "ordering": ["questionnaire", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MappingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="action"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="object id"
                    ),
                ),
                (
                    "values",
                    models.JSONField(blank=True, default=dict, verbose_name="values"),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="error"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="model",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_runs",
                        to="vinta_django_questionnaires.questionnaireresponse",
                        verbose_name="questionnaire response",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="vinta_django_questionnaires.responsemapping",
                        verbose_name="mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "mapping run",
                "verbose_name_plural": "mapping runs",
                "ordering": ["-created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["mapping", "-created_at"],
                        name="vinta_djang_mapping_3f6ad4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MappingField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("value", "Written to the record"),
                            ("lookup", "Used to find the record to update"),
                        ],
                        default="value",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="A field of the target model. Use `field__lookup` for a lookup field.",
                        max_length=255,
                        verbose_name="target field",
                    ),
                ),
                (
                    "expression",
                    models.TextField(
                        help_text="JMESPath, evaluated against the response document.",
                        verbose_name="expression",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the whole mapping is abandoned when this resolves to nothing.",
                        verbose_name="is required",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="order"),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="vinta_django_questionnaires.responsemapping",
                        verbose_name="mapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "mapping field",
                "verbose_name_plural": "mapping fields",
                "ordering": ["mapping", "role", "order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mapping", "role", "target_field"),
                        name="unique_target_field_per_mapping_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="method"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=1000, verbose_name="URL"
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="request body"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="status code"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True, default="", verbose_name="response body"
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="error"),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_deliveries",
                        to="vinta_django_questionnaires.questionnaireresponse",
                        verbose_name="questionnaire response",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="vinta_django_questionnaires.responsewebhook",
                        verbose_name="webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "-created_at"],
                        name="vinta_djang_webhook_3d9b08_idx",
                    )
                ],
            },
        ),
    ]
