# Generated by Django 6.1 on 2026-08-27 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vinta_django_questionnaires", "0008_scope_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsemapping",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Run only for responses belonging to this scope. Empty runs for every scope, which is what a single-tenant installation wants and what a shared questionnaire usually does not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to=settings.QUESTIONNAIRES_SCOPE_MODEL,
                verbose_name="scope",
            ),
        ),
        migrations.AddField(
            model_name="responsewebhook",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Run only for responses belonging to this scope. Empty runs for every scope, which is what a single-tenant installation wants and what a shared questionnaire usually does not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to=settings.QUESTIONNAIRES_SCOPE_MODEL,
                verbose_name="scope",
            ),
        ),
    ]
