# Generated by Django 6.1 on 2026-08-28 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("global", "Global"), ("scoped", "Scoped")],
                        default="global",
                        max_length=20,
                        verbose_name="scope type",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable string form of this scope. Never changes once records reference it.",
                        max_length=255,
                        verbose_name="scope key",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="label"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questionnaire_scopes",
                        to="scopedapp.organization",
                    ),
                ),
            ],
            options={
                "swappable": "QUESTIONNAIRES_SCOPE_MODEL",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("organization__isnull", True), ("scope_type", "global")
                            ),
                            models.Q(
                                models.Q(("scope_type", "global"), _negated=True),
                                ("organization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="organization_scope_type_and_value_agree",
                    )
                ],
            },
        ),
    ]
